### ISSUE TITLE
not all cars work

### ISSUE THREAD

**Issue by AtomicGaming666** [five-m/Vehicles#5]
hey so i pot all the cop cars in my server but only to of them will load

**Comment by gabrielcalderon** [comment]
I have the same problem, several of the police cars don't spawn at all. 

Ex.
Chiron
Reventon

**Comment by Declanoneil** [comment]
@gabrielcalderon and @AtomicGaming666  ill have a look at the cars and see if i can fix them if i do ill let you know

**Comment by Declanoneil** [comment]
the reason why the chiron police car doesnt work because theres is no car model for the car to work

**Comment by Declanoneil** [comment]
so basically you have every part except the frame of the car

**Comment by WajihHalawani** [comment]
Please keep in mind that not every car is tested before posting in here. But i can confirm that more than 95% of the pack is working fine.
@AtomicGaming666 

I'm closing this issue here. Thanks for the feedback!

**Comment by MisterRipley** [comment]
the nismo20 does not work it causes game to crash

**Comment by WajihHalawani** [comment]
Next time please make a new issue request and don't spam other's issues with different issues please.

And no it doesn't.
