### ISSUE TITLE
Network error 

### ISSUE THREAD

**Issue by glikx** [five-m/Vehicles#6]
**Describe the bug**

When trying to download it will hit 1.5gb done about and then will come up with an error saying network error I have tried on multiple browsers and they still don’t work 

**Expected behavior**
Click it and it install all the way fine 

**Screenshots**
![692CEAC4-1BFA-4B9B-A7B6-5E47DB115CA9](https://user-images.githubusercontent.com/65762171/95665614-02f49180-0b4a-11eb-9b87-c2a39c353653.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome,edge,Firefox

**Comment by matrix8912** [comment]
this is not about your network error.. this is about file corrupt.. try to install 7zip.. and extract it.. you can found where file on error..
i think in Mercedes-Benz/Mercedes S63 AMG Cabriolet By S4MuEL- V1.2/ have corrupter file..

sorry for my bad english ..

**Comment by WajihHalawani** [comment]
IT'S NOT NETWORK ERROR AND IT'S NOT CORRUPTED.

It's about not downloading the file corretly. There is 0 chance that it's file correpted or something else, i have uploaded all files separately.

So if you are trying to download the file on your VPS or Dedicated server and you have a not very good server it will fail, try use download manager or try to download the files directly on your PC then upload the vehicles you want to your server.

**Comment by matrix8912** [comment]
@WajihHalawani i try to much download using browser/idm on my pc but still got error network..
but when i try clone using GitHub Desktop.. working perfect... @glikx why not you try using GitHub Desktop..

<a href="https://ibb.co/Sy311Zy"><img src="https://i.ibb.co/xL7ccrL/adsad.jpg" alt="adsad" border="0"></a>

**Comment by glikx** [comment]
Will try github  desktop thanks see how it goes

**Comment by WajihHalawani** [comment]
The broswer will not be able to handle that much traffic cause it's too big i think.

You should already be using Github desktop if you're using github.com anyway.
